### ISSUE TITLE
Pull from private repo by using docker-registry info

### ISSUE THREAD

**Issue by ninhdh0** [WanderaOrg/git2kube#14]
1.  How could I pull private repo without ssh key but username password
Eg:
https://username:password@gitlab.com/private/repo
I tried and got errors: Command failed: parse https://username:password@gitlab.com/private/repo

2.  Also, it would be great if we can use docker-registry info from k8s secret

**Comment by CoufalJa** [comment]
1. Could you please send your command as a whole (without classified info) please? This is actually exactly how I am using the command to get data from private repo without issues.

2. I don't get this one, why would you need to do so? What is your use-case?

**Comment by ninhdh0** [comment]
1. Here is the simple example manifest 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: git2kube-watcher
  namespace: config
  labels:
    app: git2kube-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git2kube-watcher
  template:
    metadata:
      labels:
        app: git2kube-watcher
    spec:
      serviceAccountName: git2kube-watcher
      containers:
        - name: git2kube-prometheus-rules
          image: wanderadock/git2kube
          args:
          - 'watch'
          - 'configmap'
          - '--configmap=config'
          - '--namespace=config'
          - '--branch=master'
          - '--git=https://username:password@gitlab.com/private/repo.git'
          - '--interval=30'
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "grep -Fxq OK /tmp/health"
            initialDelaySeconds: 10
            periodSeconds: 35
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "grep -Fxq OK /tmp/health"
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
```

Error log:

```
Error: parse https://username:password@gitlab.com/private/repo.git: net/url: invalid userinfo
Usage:
  git2kube watch configmap [flags]

Flags:
      --annotation strings   annotation to add to K8s ConfigMap (format NAME=VALUE)
  -m, --configmap string     name for the resulting ConfigMap
  -h, --help                 help for configmap
  -k, --kubeconfig           true if locally stored ~/.kube/config should be used, InCluster config will be used if false (options: true|false) (default: false)
      --label strings        label to add to K8s ConfigMap (format NAME=VALUE)
      --merge-type string    how to merge ConfigMap data whether to also delete missing values or just upsert new (options: delete|upsert) (default "delete")
  -n, --namespace string     target namespace for the resulting ConfigMap (default "default")

Global Flags:
  -b, --branch string             branch name to pull (default "master")
  -c, --cache-folder string       destination on filesystem where cache of repository will be stored (default "/tmp/git2kube/data/")
      --exclude strings           regex that if is a match excludes the file from the upload, example: '*.yaml' or 'folder/*' if you want to match a folder (default [^\..*])
  -g, --git string                git repository address, either http(s) or ssh protocol has to be specified
      --healthcheck-file string   path to file where each refresh writes if it was successful or not, useful for K8s liveness/readiness probe
      --include strings           regex that if is a match includes the file in the upload, example: '*.yaml' or 'folder/*' if you want to match a folder (default [.*])
  -i, --interval int              interval in seconds in which to try refreshing ConfigMap from git (default 10)
  -l, --log-level string          command log level (options: [panic fatal error warning info debug]) (default "info")
  -p, --ssh-key string            path to the SSH private key (git repository address should be 'git@<address>', example: git@github.com:WanderaOrg/git2kube.git)

time="2018-09-07T05:19:30Z" level=error msg="Command failed: parse https://username:password@gitlab.com/private/repo.git: net/url: invalid userinfo"
```
It can be because pwd contains special characters I suppose

2. Just and idea, as we can use same credential info both git repo and registry for gitlab. That's would be nice if we can pick up secret info which is alredy stored in k8s docker-registry
